#!/usr/bin/env python3
"""C75 audit #2: the census's ``expressible_today`` flags against the runtime registry.

Why this face exists
    The census records, per model slice, whether the engine as shipped today could express it.
    That is a claim about the engine, so the only refutation that matters is a declaration the
    repo already binds: ``catalog.PROVIDERS`` -> ``fetcher_bindings`` -> ``canonical_model_ids``
    is the same runtime truth ``catalog.register_provider`` walks when it builds the registry, and
    a bound model is by definition expressible -- it is expressed, right now, in ``specs.py``, and
    the contract suite executes it. A row that reads ``false`` while its ``provider::model`` is
    bound is therefore not a conservative flag; it is a stale census row, and it silently removes
    that row from every roadmap queue (``rows_pending``, ``shipped_cover_rows``, the greedy build
    order) that filters on ``expressible_today``.

    The two faces are not symmetric, and the asymmetry is the point:
      * bound AND flagged false  -> a contradiction. The engine ships it and someone declared it.
      * unbound AND flagged true  -> legitimate. ``expressible_today`` means the engine *could*
        express it; it is not a claim that a declaration exists. So a true row with no binding is
        a to-do, not an error, and this script must not flag it.

Usage
    python3 docs/evidence/C75/census-registry-recheck.py            # read-only report
    python3 docs/evidence/C75/census-registry-recheck.py --self-test  # four in-memory tampers
    python3 docs/evidence/C75/census-registry-recheck.py --write      # flip the one row, once

    ``--write`` is one shot: re-running reads "moved 0" and aborts, which is the applied reading.
    Nothing here talks to a provider; the census row is rewritten from the declaration already on
    disk, and the roadmap is regenerated by its own generator afterwards:

      python3 scripts/quality/model_capability_census.py --round-id C75 \
          --json "docs/迭代计划/迭代2-统一Provider架构与全量能力补齐/capability-roadmap.json"
"""

from __future__ import annotations

import copy
import csv
import hashlib
import json
import sys
from pathlib import Path
from typing import Final

REPO_ROOT = Path(__file__).resolve().parents[3]
PLAN_DIR: Final = "docs/迭代计划/迭代2-统一Provider架构与全量能力补齐"
CENSUS_GLOB: Final = "census-*.json"
AUDIT_FILE: Final = f"{PLAN_DIR}/census-audit.json"
LEDGER_CSV: Final = "模型级任务清单.csv"
EXPECTED_CENSUS_ROWS: Final = 150
AUDITED_BY: Final = "C75 census-vs-registry recheck"
AUDITED_DATE: Final = "2026-10-09"


def _sha(path: Path) -> str:
    """Digest of a file as it sits on disk right now."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def bound_models() -> dict[str, set[str]]:
    """The runtime truth: model ids the registered descriptors bind, per provider source."""
    sys.path.insert(0, str(REPO_ROOT))
    from opendata.data.providers import catalog

    face: dict[str, set[str]] = {}
    for descriptor in catalog.PROVIDERS:
        ids = {
            str(model_id)
            for binding in getattr(descriptor, "fetcher_bindings", ()) or ()
            for model_id in getattr(binding, "canonical_model_ids", ())
        }
        if ids:
            face[descriptor.source] = ids
    return face


def census_files() -> list[Path]:
    """Every census file the roadmap loads, excluding the audit artifact that carries no rows."""
    out: list[Path] = []
    for path in sorted((REPO_ROOT / PLAN_DIR).glob(CENSUS_GLOB)):
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict) and isinstance(data.get("rows"), list):
            out.append(path)
    return out


def load_rows(files: list[Path]) -> list[dict[str, object]]:
    """Every census row, with the file it came from attached for the write path."""
    rows: list[dict[str, object]] = []
    for path in files:
        for row in json.loads(path.read_text(encoding="utf-8"))["rows"]:
            row["_file"] = str(path)
            rows.append(row)
    return rows


def contradictions(
    rows: list[dict[str, object]], bound: dict[str, set[str]]
) -> list[dict[str, object]]:
    """Rows reading ``expressible_today: false`` whose provider::model the registry binds."""
    return [
        row
        for row in rows
        if not row.get("expressible_today")
        and row.get("upstream_model") in bound.get(str(row.get("provider")), set())
    ]


def declared_but_unflagged(rows: list[dict[str, object]], bound: dict[str, set[str]]) -> int:
    """Rows reading true with no binding: a queue, not an error. Counted so the face is visible."""
    return sum(
        1
        for row in rows
        if row.get("expressible_today")
        and row.get("upstream_model") not in bound.get(str(row.get("provider")), set())
    )


def bound_true(
    rows: list[dict[str, object]], bound: dict[str, set[str]]
) -> list[dict[str, object]]:
    """Rows the registry binds AND the census already flags true -- the census's clean majority."""
    return [
        row
        for row in rows
        if row.get("expressible_today")
        and row.get("upstream_model") in bound.get(str(row.get("provider")), set())
    ]


def scope_face(rows: list[dict[str, object]], bound: dict[str, set[str]]) -> tuple[int, list[str]]:
    """How many bound models the 150-row census even carries, and which ones it is out of scope for.

    The census is not the ledger: ``census-audit.json`` records 150 rows + 185 credential-gated +
    15 in-progress = the 350-row ledger total, and its provider_groups name 16 providers, none of
    them fred/ecb/bls/fmp. So a bound model with no census row is out of that file's scope, not
    lost -- but the face has to be printed, or a later reader re-derives it as a defect.
    """
    censused = {(str(row.get("provider")), str(row.get("upstream_model"))) for row in rows}
    outside = [
        f"{source}::{model_id}"
        for source in sorted(bound)
        for model_id in sorted(bound[source])
        if (source, model_id) not in censused
    ]
    bound_total = sum(len(ids) for ids in bound.values())
    return bound_total - len(outside), outside


def in_progress_face(bound: dict[str, set[str]]) -> tuple[int, list[str], list[str]]:
    """The IN_PROGRESS ledger rows, split by whether the runtime registry already binds them.

    This is the face that answers "are those rows actually being finished?". A bound row's code is
    installed and executed by the contract suite, so what is outstanding is a witness, a rights
    registration or a key decision -- not dev. An unbound row still has a client/Fetcher to ship.
    """
    with (REPO_ROOT / PLAN_DIR / LEDGER_CSV).open(newline="", encoding="utf-8") as handle:
        rows = [
            r for r in csv.DictReader(handle) if r["implementation_task_status"] == "IN_PROGRESS"
        ]
    binding, outstanding = [], []
    for record in rows:
        name = f"{record['provider']}::{record['upstream_model']}"
        (
            binding
            if record["upstream_model"] in bound.get(record["provider"], set())
            else outstanding
        ).append(name)
    return len(rows), sorted(binding), sorted(outstanding)


def ledger_identity(rows: list[dict[str, object]]) -> dict[str, object]:
    """Recompute the census/ledger split from the ledger itself and compare it with the typed audit.

    The first draft of this check compared only the SUM, and the sum closed: 150 + (185 + 15) = 350.
    Recomputing the LEAVES shows that is two offsetting errors, not agreement: the ledger has 152
    rows for the census's 16 providers (the census carries 150), and 13 IN_PROGRESS rows, not 15.
    A sum that closes over a wrong composition is the failure this check exists to catch.
    """
    audit = json.loads((REPO_ROOT / AUDIT_FILE).read_text(encoding="utf-8"))
    census_providers = {str(row.get("provider")) for row in rows}
    typed_out = {str(k): int(v) for k, v in (audit.get("out_of_scope_rows") or {}).items()}
    with (REPO_ROOT / PLAN_DIR / LEDGER_CSV).open(newline="", encoding="utf-8") as handle:
        ledger = list(csv.DictReader(handle))
    inside = [r for r in ledger if r["provider"] in census_providers]
    outside = [r for r in ledger if r["provider"] not in census_providers]
    rec_status: dict[str, int] = {}
    for record in outside:
        key = f"{record['implementation_task_status'].lower()}_out_of_census_provider"
        rec_status[key] = rec_status.get(key, 0) + 1
    absent = [
        f"{record['provider']}::{record['upstream_model']}({record['implementation_task_status']})"
        for record in inside
        if (record["provider"], record["upstream_model"])
        not in {(str(r.get("provider")), str(r.get("upstream_model"))) for r in rows}
    ]
    return {
        "ledger_rows": len(ledger),
        "typed_census_rows": int(audit.get("recomputed_total") or -1),
        "ledger_rows_for_census_providers": len(inside),
        "typed_out": typed_out,
        "recomputed_out": rec_status,
        "typed_total": int(audit.get("ledger_total") or -1),
        "sum_closes": int(audit.get("recomputed_total") or -1) + sum(typed_out.values())
        == len(ledger)
        == int(audit.get("ledger_total") or -1),
        "leaves_close": sum(typed_out.values()) == len(outside),
        "rows_missing_from_census": absent,
    }


def apply_write(targets: list[dict[str, object]]) -> int:
    """Rewrite each target row in place: true, no engine work outstanding, audited with carriers."""
    moved = 0
    for row in targets:
        path = Path(str(row["_file"]))
        data = json.loads(path.read_text(encoding="utf-8"))
        for stored in data["rows"]:
            if stored.get("task_id") != row.get("task_id"):
                continue
            stored["expressible_today"] = True
            stored["needs_engine_capability"] = []
            stored["audited"] = {
                "audited_by": AUDITED_BY,
                "audited_date": AUDITED_DATE,
                "basis": str(row["_audit_basis"]),
            }
            moved += 1
        text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(path)
    return moved


def tampers(rows: list[dict[str, object]], bound: dict[str, set[str]]) -> list[str]:
    """Four in-memory controls; each returns the reading it must produce, never touching disk."""
    notes: list[str] = []
    live = contradictions(rows, bound)

    # T1 -- positive control on the row side: the flagged row, set true, must leave the face.
    flipped = copy.deepcopy(rows)
    for row in flipped:
        if row.get("task_id") == "OBB2-cboe-IndexSearch":
            row["expressible_today"] = True
    if contradictions(flipped, bound):
        notes.append("T1 FAIL: flipping the row still reads as a contradiction")
    else:
        notes.append("T1 ok: row-side flip clears the face (the face is driven by the flag)")

    # T2 -- positive control on the binding side: drop cboe's binding, the face must go quiet too.
    unbinned = dict(bound)
    unbinned.pop("cboe", None)
    if contradictions(rows, unbinned):
        notes.append("T2 FAIL: the face survives without the binding")
    else:
        notes.append("T2 ok: removing the binding clears the face (it is driven by runtime truth)")

    # T3 -- the asymmetry, both sides: a row whose flag is true AND whose binding is absent must
    # move to the queue and must never be charged as an error. Isolated from the live hits, which
    # would otherwise keep the face non-empty and make this control false-fail.
    hit_ids = {str(row.get("task_id")) for row in live}
    queue_before = declared_but_unflagged(rows, bound)
    t3 = copy.deepcopy(rows)
    for row in t3:
        if str(row.get("task_id")) in hit_ids:
            row["expressible_today"] = True
            row["provider"] = "__not_a_registered_source__"
    queue_after = declared_but_unflagged(t3, bound)
    charged = contradictions(t3, bound)
    if charged or queue_after != queue_before + len(hit_ids):
        notes.append(
            f"T3 FAIL: unbound-but-true charged={len(charged)} queue {queue_before}->{queue_after} "
            f"(expected +{len(hit_ids)})"
        )
    else:
        notes.append(
            f"T3 ok: unbound-but-true stays a queue, never an error (declarable != declared; "
            f"queue {queue_before}->{queue_after})"
        )

    # T4 -- a bound row nobody flagged must be found. The seed target is taken from the census
    # itself, not typed: the first draft named OBB2-cboe-AvailableIndices, a row that does not
    # exist, so the loop set nothing and the control printed a silent zero. Existence is now a
    # face, and a missing seed is a loud FAIL rather than an empty set.
    seeds = bound_true(rows, bound)
    if not seeds:
        notes.append("T4 FAIL: no bound-and-true row exists to seed a contradiction from")
    else:
        seeded = copy.deepcopy(rows)
        target = str(seeds[0]["task_id"])
        for row in seeded:
            if str(row.get("task_id")) == target:
                row["expressible_today"] = False
        found = {str(row.get("task_id")) for row in contradictions(seeded, bound)}
        if target in found and len(found) == len(hit_ids) + 1:
            notes.append(
                f"T4 ok: seeding {target} grew the face {len(hit_ids)}->{len(found)} "
                f"(a new contradiction is caught, not swallowed)"
            )
        else:
            notes.append(
                f"T4 FAIL: seeded {target} not in face; face={sorted(found)} expected "
                f"{sorted(hit_ids | {target})}"
            )
    return notes


def main(argv: list[str]) -> int:
    """Report, self-test, or apply the one-row rewrite."""
    self_test = "--self-test" in argv
    write = "--write" in argv
    files = census_files()
    rows = load_rows(files)
    bound = bound_models()
    if len(rows) != EXPECTED_CENSUS_ROWS:
        print(f"ABORT: census rows = {len(rows)}, expected {EXPECTED_CENSUS_ROWS}")
        return 1
    digests = {path.name: _sha(path) for path in files}

    print(f"census files: {len(files)} -> {sorted(digests)}")
    print(f"census rows: {len(rows)} (guard {EXPECTED_CENSUS_ROWS})")
    print(f"bound providers: {len(bound)}  bound model ids: {sum(len(v) for v in bound.values())}")
    for source in sorted(bound):
        print(f"  {source:<16} {sorted(bound[source])}")

    hits = contradictions(rows, bound)
    print(f"\ncontradiction face (bound AND flagged false) = {len(hits)}")
    for row in hits:
        print(f"  {row['task_id']:<40} needs={sorted(row.get('needs_engine_capability') or [])}")
    true_rows = [row for row in rows if row.get("expressible_today")]
    bound_true_rows = bound_true(rows, bound)
    print(
        f"flagged true total = {len(true_rows)}  of which bound = {len(bound_true_rows)}  "
        f"unbound = {len(true_rows) - len(bound_true_rows)}"
    )
    print(
        f"identity: total == bound + unbound -> "
        f"{len(true_rows) == len(bound_true_rows) + (len(true_rows) - len(bound_true_rows))}"
    )
    print(f"rows_expressible_today after the rewrite must read {len(true_rows) + len(hits)}")
    print(f"true-but-unbound (a queue, not an error) = {declared_but_unflagged(rows, bound)}")

    inside, outside = scope_face(rows, bound)
    print(
        f"\ncensus scope face: bound model ids = {inside + len(outside)} "
        f"= in-census {inside} + out-of-census-scope {len(outside)}"
    )
    for name in outside:
        print(f"  out of scope: {name}")
    ident = ledger_identity(rows)
    print(
        f"\nledger arithmetic: census {ident['typed_census_rows']} + out-of-scope "
        f"{sum(ident['typed_out'].values())} == ledger {ident['ledger_rows']} -> "
        f"sum closes={ident['sum_closes']}"
    )
    print(f"  typed out_of_scope_rows  = {ident['typed_out']}")
    print(f"  recomputed out of scope  = {ident['recomputed_out']}")
    print(f"  leaves close (typed == recomputed) = {ident['leaves_close']}")
    print(
        f"  ledger rows for census providers = "
        f"{ident['ledger_rows_for_census_providers']} vs census rows "
        f"{ident['typed_census_rows']}"
    )
    if ident["rows_missing_from_census"]:
        print(f"  census-provider rows with NO census row: {ident['rows_missing_from_census']}")
    if not ident["leaves_close"]:
        print("  COMPOSITION MISMATCH: the sum closes over a wrong split, so census-audit.json's")
        print("  out_of_scope_rows is stale. Reported, not repaired here -- it is a typed tally,")
        print("  and the 150-row denominator stays as it is.")
    total_ip, bound_ip, outstanding_ip = in_progress_face(bound)
    print(
        f"\nIN_PROGRESS ledger rows = {total_ip}: registry-bound = {len(bound_ip)}, "
        f"client/Fetcher outstanding = {len(outstanding_ip)}"
    )
    for name in bound_ip:
        print(f"  bound, dev installed: {name}")
    for name in outstanding_ip:
        print(f"  NOT bound, dev left : {name}")

    if self_test:
        notes = tampers(rows, bound)
        for note in notes:
            print(note)
        failed = [note for note in notes if "FAIL" in note]
        print(
            f"SELF-TEST: {len(notes) - len(failed)}/{len(notes)} controls agreed"
            if not failed
            else "SELF-TEST FAILED"
        )
        return 1 if failed else 0

    if write:
        if len(hits) != 1:
            print(f"ABORT: expected exactly 1 row to move, found {len(hits)}")
            return 1
        row = hits[0]
        row["_audit_basis"] = (
            "opendata/data/providers/cboe/specs.py declares the IndexSearch ModelSpec with a "
            "declared RowFilterSpec, catalog.PROVIDERS binds cboe::IndexSearch through "
            "fetcher_bindings.canonical_model_ids, tests/test_engine_row_filters.py executes the "
            "filter, and 模型级任务清单.csv already reads implementation_task_status=DEV_DONE for "
            "that row -- so the engine expresses this slice today and the census flag was stale."
        )
        moved = apply_write([row])
        print(f"applied: {moved} row(s) rewritten in {Path(str(row['_file'])).name}")
        for path in files:
            after = _sha(path)
            tag = "changed" if after != digests[path.name] else "intact"
            print(f"  {path.name}: {tag}")
        return 0

    print("\nDRY RUN -- census untouched. Pass --write, then regenerate the roadmap.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
