"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-22 16:40:55.593775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Perform database upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_id', sa.String(length=100), nullable=False),
    sa.Column('script_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_category', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.Enum('HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'ONCE', 'MANUAL', name='scriptfrequency'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('target_table', sa.String(length=100), nullable=True),
    sa.Column('module_path', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_data_scripts_category'), 'data_scripts', ['category'], unique=False)
    op.create_index(op.f('ix_data_scripts_is_custom'), 'data_scripts', ['is_custom'], unique=False)
    op.create_index(op.f('ix_data_scripts_script_id'), 'data_scripts', ['script_id'], unique=True)
    op.create_index(op.f('ix_data_scripts_sub_category'), 'data_scripts', ['sub_category'], unique=False)
    op.create_index(op.f('ix_data_scripts_target_table'), 'data_scripts', ['target_table'], unique=False)
    op.create_table('data_tables',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('table_comment', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('script_id', sa.String(length=100), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('last_update_time', sa.DateTime(), nullable=True),
    sa.Column('last_update_status', sa.Enum('success', 'failed', name='update_status'), nullable=True),
    sa.Column('data_start_date', sa.Date(), nullable=True),
    sa.Column('data_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_data_tables_category'), 'data_tables', ['category'], unique=False)
    op.create_index(op.f('ix_data_tables_last_update_time'), 'data_tables', ['last_update_time'], unique=False)
    op.create_index(op.f('ix_data_tables_script_id'), 'data_tables', ['script_id'], unique=False)
    op.create_index(op.f('ix_data_tables_table_name'), 'data_tables', ['table_name'], unique=True)
    op.create_table('interface_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_interface_categories_name'), 'interface_categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('data_interfaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('module_path', sa.String(length=255), nullable=True),
    sa.Column('function_name', sa.String(length=100), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('return_type', sa.String(length=50), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['interface_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_data_interfaces_name'), 'data_interfaces', ['name'], unique=True)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.String(length=100), nullable=False),
    sa.Column('schedule_type', sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'MONTHLY', 'CRON', 'INTERVAL', name='scheduletype'), nullable=False),
    sa.Column('schedule_expression', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('retry_on_failure', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['data_scripts.script_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index('ix_scheduled_tasks_user_active', 'scheduled_tasks', ['user_id', 'is_active'], unique=False)
    op.create_table('interface_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('param_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'DATE', 'LIST', 'OPTION', name='parametertype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['data_interfaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=100), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('script_id', sa.String(length=100), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_trace', sa.Text(), nullable=True),
    sa.Column('rows_before', sa.Integer(), nullable=True),
    sa.Column('rows_after', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Enum('SCHEDULER', 'MANUAL', 'API', name='triggeredby'), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_task_executions_execution_id'), 'task_executions', ['execution_id'], unique=True)
    op.create_index('ix_task_executions_script_id', 'task_executions', ['script_id'], unique=False)
    op.create_index('ix_task_executions_start_time', 'task_executions', ['start_time'], unique=False)
    op.create_index(op.f('ix_task_executions_status'), 'task_executions', ['status'], unique=False)
    op.create_index('ix_task_executions_task_status', 'task_executions', ['task_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform database downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_executions_task_status', table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_status'), table_name='task_executions')
    op.drop_index('ix_task_executions_start_time', table_name='task_executions')
    op.drop_index('ix_task_executions_script_id', table_name='task_executions')
    op.drop_index(op.f('ix_task_executions_execution_id'), table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_table('interface_parameters')
    op.drop_index('ix_scheduled_tasks_user_active', table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_data_interfaces_name'), table_name='data_interfaces')
    op.drop_table('data_interfaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_interface_categories_name'), table_name='interface_categories')
    op.drop_table('interface_categories')
    op.drop_index(op.f('ix_data_tables_table_name'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_script_id'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_last_update_time'), table_name='data_tables')
    op.drop_index(op.f('ix_data_tables_category'), table_name='data_tables')
    op.drop_table('data_tables')
    op.drop_index(op.f('ix_data_scripts_target_table'), table_name='data_scripts')
    op.drop_index(op.f('ix_data_scripts_sub_category'), table_name='data_scripts')
    op.drop_index(op.f('ix_data_scripts_script_id'), table_name='data_scripts')
    op.drop_index(op.f('ix_data_scripts_is_custom'), table_name='data_scripts')
    op.drop_index(op.f('ix_data_scripts_category'), table_name='data_scripts')
    op.drop_table('data_scripts')
    # ### end Alembic commands ###
