/**
 * Auto-generated API Types - DO NOT EDIT
 * Generated by openapi-typescript from FastAPI OpenAPI schema
 */

export interface paths {
  [key: string]: {
    get?: operations
    post?: Operation
    delete?: Operation
    put?: Operation
    parameters?: {
      path?: {
        name?: string
        in?: string
        required?: boolean
        schema?: {
          type: string
        }
      }
    }
    body?: {
      content?: unknown
      description?: string
    }
  }
}

export interface Operation {
  parameters?: unknown[]
  responses?: {
    [key: string]: {
      description?: string
      content?: {
        [key: string]: {
          schema?: unknown
        }
      }
    }
  }
}

export interface operations {
  [key: string]: Operation
}
